In [154]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# Bagian Baru

In [155]:
wn_dataset = pd.read_csv('sample_data/Customertravel.csv')

In [156]:
wn_dataset.head()

Age  FrequentFlyer  AnnualIncomeClass  ServicesOpted  \
0   34              0                  2              6   
1   34              1                  1              5   
2   37              0                  2              3   
3   30              0                  2              2   
4   30              0                  1              1   

   AccountSyncedToSocialMedia  BookedHotelOr0t  Target  
0                           0                1       0  
1                           1                0       1  
2                           1                0       0  
3                           0                0       0  
4                           0                0       0

In [157]:
wn_dataset.shape

(954, 7)

In [158]:
# memisahkan data dan label

x = wn_dataset.drop (columns='AnnualIncomeClass', axis=1)
y = wn_dataset['AnnualIncomeClass']

In [159]:
print(x)

     Age  FrequentFlyer  ServicesOpted  AccountSyncedToSocialMedia  \
0     34              0              6                           0   
1     34              1              5                           1   
2     37              0              3                           1   
3     30              0              2                           0   
4     30              0              1                           0   
..   ...            ...            ...                         ...   
949   31              1              1                           0   
950   30              0              5                           0   
951   37              0              4                           0   
952   30              0              1                           1   
953   31              1              1                           0   

     BookedHotelOr0t  Target  
0                  1       0  
1                  0       1  
2                  0       0  
3                  0       0  
4   

In [160]:
print(y)

0      2
1      1
2      2
3      2
4      1
      ..
949    1
950    2
951    2
952    1
953    3
Name: AnnualIncomeClass, Length: 954, dtype: int64


In [161]:
# standarisasi data

scaler = StandardScaler() 

In [162]:
scaler.fit(x)

StandardScaler()

In [163]:
standar_data = scaler.transform(x)

In [164]:
print(standar_data)

[[ 0.56690365 -0.65432692  2.21932995 -0.77849894  1.2344268  -0.55393981]
 [ 0.56690365  1.52828804  1.59642887  1.28452326 -0.81009259  1.80525028]
 [ 1.46628183 -0.65432692  0.35062671  1.28452326 -0.81009259 -0.55393981]
 ...
 [ 1.46628183 -0.65432692  0.97352779 -0.77849894 -0.81009259 -0.55393981]
 [-0.63226726 -0.65432692 -0.89517545  1.28452326  1.2344268  -0.55393981]
 [-0.33247453  1.52828804 -0.89517545 -0.77849894 -0.81009259 -0.55393981]]


In [165]:
x = standar_data
y = wn_dataset['AnnualIncomeClass']

In [166]:
print(x)
print(y)

[[ 0.56690365 -0.65432692  2.21932995 -0.77849894  1.2344268  -0.55393981]
 [ 0.56690365  1.52828804  1.59642887  1.28452326 -0.81009259  1.80525028]
 [ 1.46628183 -0.65432692  0.35062671  1.28452326 -0.81009259 -0.55393981]
 ...
 [ 1.46628183 -0.65432692  0.97352779 -0.77849894 -0.81009259 -0.55393981]
 [-0.63226726 -0.65432692 -0.89517545  1.28452326  1.2344268  -0.55393981]
 [-0.33247453  1.52828804 -0.89517545 -0.77849894 -0.81009259 -0.55393981]]
0      2
1      1
2      2
3      2
4      1
      ..
949    1
950    2
951    2
952    1
953    3
Name: AnnualIncomeClass, Length: 954, dtype: int64


In [167]:
# memisahkan data training dan data testing

X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size= 0.3, stratify=y, random_state=3)

In [168]:
print(x.shape, X_train.shape, X_test.shape) 

(954, 6) (667, 6) (287, 6)


In [169]:
# membuat data latih menggunakan algoritma SVM

classifier = svm.SVC(kernel='linear')

In [170]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [171]:
#membuat evaluasi untuk mengukur tingkat akurasi

X_train_predic = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_predic, Y_train)

In [172]:
print('Akurasi data training adalah = ', training_data_accuracy)

Akurasi data training adalah =  0.6866566716641679


In [173]:
X_test_predic = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_predic, Y_test)

In [174]:
print('Akurasi data testing adalah = ', test_data_accuracy)

Akurasi data testing adalah =  0.6898954703832753


In [182]:
# membuat model prediksi

input_data = (34,1,5,1,0,1)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

predic = classifier.predict(std_data)
print(predic)

if (predic == 1 ):
    print('Low ')
if (predic == 2 ):
    print('Midle')
else :
    print('Hight')

[[ 0.56690365  1.52828804  1.59642887  1.28452326 -0.81009259  1.80525028]]
[1]
Low 
Hight


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [179]:
# simpan model

import pickle

In [181]:
filename = 'Customertravel.sav'
pickle.dump(classifier, open(filename,'wb'))